### ISSUE TITLE
[Bug] Crashes when clicking on the creative menu tab when used with ModernFix's dynamic resources option [Fabric 1.20.1/0.16.7]

### ISSUE THREAD

**Issue by pokesmells** [ArkTechMC/MowziesMobs-Fabric#4]
https://mclo.gs/mIQYstx

**Comment by IAFEnvoy** [comment]
ModernFix author has said that model modification may cause incapability with other mods. So just close it.

https://github.com/embeddedt/ModernFix/wiki/Dynamic-Resources-FAQ

**Comment by pokesmells** [comment]
I'm not going to do that, it's legitimately a staple and default option for many large fabric modpacks to improve load times on start-up.

Many other mods have fixed this so please fix it later on.
